
spring.application.name=cwslife

# Backend runs on this port
server.port=8080

# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/cwslife_db
spring.datasource.username=root
spring.datasource.password=Root@123
# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#  EMAIL CONFIGURATION 
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=noreply.creativewebsolution@gmail.com
spring.mail.password=hshy weit hypz slzj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# EMAIL CONFIGURATION - GoDaddy
#spring.mail.host=smtpout.secureserver.net
#spring.mail.port=465
##put your cws email id below
#spring.mail.username=noreply.creativewebsolution@gmail.com
##put your email password
#spring.mail.password=Cre@t!veWeb32
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.ssl.enable=true
#spring.mail.properties.mail.smtp.starttls.enable=false
#spring.mail.properties.mail.smtp.ssl.trust=smtpout.secureserver.net

# Frontend URL reset link 
app.frontend.url=app-lifeqa-fe.azurewebsites.net

# File upload settings
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Upload folder path
app.upload.dir=/home/site/wwwroot/uploads/events
